name: Install Playwright
description: Install Playwright browsers and system dependencies for CI

runs:
  using: composite
  steps:
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      shell: bash
