name: "d. j. graham"
description: "a triumph of style over substance"
permalink: pretty
baseurl: "http://deejaygraham.github.io"
twitterurl: http://twitter.com/deejaygraham
email: deejaygraham@gmail.com
markdown: rdiscount
pygments: true
paginate: 5
exclude: [ make.cmd ]
