# meta
name: "invalid argument"
description: "a triumph of style over substance"
author: d.j.graham
repository: "deejaygraham/deejaygraham.github.io"

# options
permalink: /:year/:month/:day/:title/
paginate: 12
exclude: [make.cmd, build.sh, buildsite.msbuild, post.rb]
#syntax-theme: prism-atom-dark

# collections
collections:
  category:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"

# css processing
sass:
  style: compressed

# external links
twitterid: deejaygraham
twitterurl: http://twitter.com/deejaygraham
email: deejaygraham@gmail.com
emaillink: mailto:deejaygraham@gmail.com
githuburl: https://github.com/deejaygraham
gisturl: https://gist.github.com/deejaygraham
codeplexurl: https://www.codeplex.com/site/users/view/deejaygraham
linkedinurl: https://uk.linkedin.com/in/derekjohngraham
instagramurl: https://www.instagram.com/dee.jay.graham/
slideshareurl: https://www.slideshare.net/deejaygraham
