#!/bin/bash
set -e

# Nicked (with thanks) from Tim Ottinger

# Check if remote origin exists
if git remote | grep -q origin; then
    git pull --rebase
else
    if [ -n "$(git ls-files --others --modified --exclude-standard)" ]; 
    then
	git status
	exit 1
    fi
    echo "No remote origin configured, skipping git pull"
fi
