name: A11y Tests
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
    
      - name: Install Playwright
        uses: ./.github/actions/install-playwright
        
      - name: Run Playwright tests
        uses: ./.github/actions/run-playwright
        with:
          playwright_cli_args: "--grep @a11y"
        
      - name: Upload Playwright report
        uses: ./.github/actions/upload-playwright-report
