name: Validate

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.gitignore'
      - '_drafts/**'
      - 'cypress/**'
      - 'tests/**'
      
  workflow_dispatch:

jobs:
  validate_code:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use current Node version
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Lint javascript
        run: npm run lint
        continue-on-error: false
          
      - name: Unit test 11ty code
        run: npm run unit-test
        continue-on-error: false
