name: Validate

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.gitignore'
      - '_drafts/**'
      - 'cypress/**'
      - 'tests/**'
      
  workflow_dispatch:

jobs:
  validate_code:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use current Node version
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Lint javascript
        id: eslint
        run: |
          npm run lint
          echo "::set-output name=eslint_exit_code::$?"

      - name: Fail if ESLint errors
          if: steps.eslint.outputs.eslint_exit_code != 0
          run: exit 1

      - name: Unit test 11ty code
        run: npm run unit-test
