name: Validate

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.gitignore'
      - '_drafts/**'
      - 'tests/**'
      
  workflow_dispatch:

jobs:
  validate_code:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set GITHUB_HEAD_SHA environment variable
        shell: bash
        run: |
          echo GITHUB_HEAD_SHA=${{ github.repository }}:${{ github.workflow }} >> $GITHUB_ENV

      - name: Debug environment variables
        shell: bash
        run: |
          echo "GITHUB_HEAD_SHA=$GITHUB_HEAD_SHA"
        
      - name: Setup Node CI
        uses: ./.github/actions/setup-node-ci

      - name: Lint javascript
        run: npx eslint . --max-warnings=0 

      - name: Lint markdown
        run: npm run mdlint

      - name: Lint post tags
        run: npm run lint:tags

      - name: Lint post frontmatter and content
        run: npm run lint:posts
        
      - name: Run unit tests
        run: npm run unit-test
